// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: posts/post_input.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubjectClassId   string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId   string                 `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Type             PostType               `protobuf:"varint,4,opt,name=type,proto3,enum=posts.PostType" json:"type,omitempty"`
	TypeId           string                 `protobuf:"bytes,5,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Title            string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	FileType         string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	StorageId        string                 `protobuf:"bytes,9,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source           string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	IsAllowToComment bool                   `protobuf:"varint,11,opt,name=is_allow_to_comment,json=isAllowToComment,proto3" json:"is_allow_to_comment,omitempty"`
	IsPublished      bool                   `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_posts_post_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_post_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_post_input_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *CreatePostRequest) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *CreatePostRequest) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_UNKNOWN
}

func (x *CreatePostRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePostRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *CreatePostRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *CreatePostRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreatePostRequest) GetIsAllowToComment() bool {
	if x != nil {
		return x.IsAllowToComment
	}
	return false
}

func (x *CreatePostRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type UpdatePostRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId   string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId   string                 `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	TypeId           string                 `protobuf:"bytes,5,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Title            string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	FileType         string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	StorageId        string                 `protobuf:"bytes,9,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source           string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	IsAllowToComment bool                   `protobuf:"varint,11,opt,name=is_allow_to_comment,json=isAllowToComment,proto3" json:"is_allow_to_comment,omitempty"`
	IsPublished      bool                   `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_posts_post_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_post_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_post_input_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePostRequest) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *UpdatePostRequest) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *UpdatePostRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePostRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UpdatePostRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *UpdatePostRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdatePostRequest) GetIsAllowToComment() bool {
	if x != nil {
		return x.IsAllowToComment
	}
	return false
}

func (x *UpdatePostRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,3,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_posts_post_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_post_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_posts_post_input_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *CreateCommentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateCommentRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *CreateCommentRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_posts_post_input_proto protoreflect.FileDescriptor

const file_posts_post_input_proto_rawDesc = "" +
	"\n" +
	"\x16posts/post_input.proto\x12\x05posts\x1a\x18posts/post_message.proto\"\x83\x03\n" +
	"\x11CreatePostRequest\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x03 \x01(\tR\x0etopicSubjectId\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.posts.PostTypeR\x04type\x12\x17\n" +
	"\atype_id\x18\x05 \x01(\tR\x06typeId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"storage_id\x18\t \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12-\n" +
	"\x13is_allow_to_comment\x18\v \x01(\bR\x10isAllowToComment\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\"\xee\x02\n" +
	"\x11UpdatePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x03 \x01(\tR\x0etopicSubjectId\x12\x17\n" +
	"\atype_id\x18\x05 \x01(\tR\x06typeId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"storage_id\x18\t \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12-\n" +
	"\x13is_allow_to_comment\x18\v \x01(\bR\x10isAllowToComment\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\"\x8b\x01\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x03 \x01(\tR\vstudentName\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acommentB\x10Z\x0epb/posts;postsb\x06proto3"

var (
	file_posts_post_input_proto_rawDescOnce sync.Once
	file_posts_post_input_proto_rawDescData []byte
)

func file_posts_post_input_proto_rawDescGZIP() []byte {
	file_posts_post_input_proto_rawDescOnce.Do(func() {
		file_posts_post_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_post_input_proto_rawDesc), len(file_posts_post_input_proto_rawDesc)))
	})
	return file_posts_post_input_proto_rawDescData
}

var file_posts_post_input_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_posts_post_input_proto_goTypes = []any{
	(*CreatePostRequest)(nil),    // 0: posts.CreatePostRequest
	(*UpdatePostRequest)(nil),    // 1: posts.UpdatePostRequest
	(*CreateCommentRequest)(nil), // 2: posts.CreateCommentRequest
	(PostType)(0),                // 3: posts.PostType
}
var file_posts_post_input_proto_depIdxs = []int32{
	3, // 0: posts.CreatePostRequest.type:type_name -> posts.PostType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_posts_post_input_proto_init() }
func file_posts_post_input_proto_init() {
	if File_posts_post_input_proto != nil {
		return
	}
	file_posts_post_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_post_input_proto_rawDesc), len(file_posts_post_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_posts_post_input_proto_goTypes,
		DependencyIndexes: file_posts_post_input_proto_depIdxs,
		MessageInfos:      file_posts_post_input_proto_msgTypes,
	}.Build()
	File_posts_post_input_proto = out.File
	file_posts_post_input_proto_goTypes = nil
	file_posts_post_input_proto_depIdxs = nil
}
