// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: posts/post_service.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_posts_post_service_proto protoreflect.FileDescriptor

const file_posts_post_service_proto_rawDesc = "" +
	"\n" +
	"\x18posts/post_service.proto\x12\x05posts\x1a\x1bposts/generic_message.proto\x1a\x16posts/post_input.proto\x1a\x18posts/post_message.proto2\x8c\x02\n" +
	"\x05Posts\x125\n" +
	"\n" +
	"CreatePost\x12\x18.posts.CreatePostRequest\x1a\v.posts.Post\"\x00\x125\n" +
	"\n" +
	"UpdatePost\x12\x18.posts.UpdatePostRequest\x1a\v.posts.Post\"\x00\x12#\n" +
	"\aGetPost\x12\t.posts.Id\x1a\v.posts.Post\"\x00\x120\n" +
	"\rUnpublishPost\x12\t.posts.Id\x1a\x12.posts.BoolMessage\"\x00\x12>\n" +
	"\rCreateComment\x12\x1b.posts.CreateCommentRequest\x1a\x0e.posts.Comment\"\x00B\x10Z\x0epb/posts;postsb\x06proto3"

var file_posts_post_service_proto_goTypes = []any{
	(*CreatePostRequest)(nil),    // 0: posts.CreatePostRequest
	(*UpdatePostRequest)(nil),    // 1: posts.UpdatePostRequest
	(*Id)(nil),                   // 2: posts.Id
	(*CreateCommentRequest)(nil), // 3: posts.CreateCommentRequest
	(*Post)(nil),                 // 4: posts.Post
	(*BoolMessage)(nil),          // 5: posts.BoolMessage
	(*Comment)(nil),              // 6: posts.Comment
}
var file_posts_post_service_proto_depIdxs = []int32{
	0, // 0: posts.Posts.CreatePost:input_type -> posts.CreatePostRequest
	1, // 1: posts.Posts.UpdatePost:input_type -> posts.UpdatePostRequest
	2, // 2: posts.Posts.GetPost:input_type -> posts.Id
	2, // 3: posts.Posts.UnpublishPost:input_type -> posts.Id
	3, // 4: posts.Posts.CreateComment:input_type -> posts.CreateCommentRequest
	4, // 5: posts.Posts.CreatePost:output_type -> posts.Post
	4, // 6: posts.Posts.UpdatePost:output_type -> posts.Post
	4, // 7: posts.Posts.GetPost:output_type -> posts.Post
	5, // 8: posts.Posts.UnpublishPost:output_type -> posts.BoolMessage
	6, // 9: posts.Posts.CreateComment:output_type -> posts.Comment
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_posts_post_service_proto_init() }
func file_posts_post_service_proto_init() {
	if File_posts_post_service_proto != nil {
		return
	}
	file_posts_generic_message_proto_init()
	file_posts_post_input_proto_init()
	file_posts_post_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_post_service_proto_rawDesc), len(file_posts_post_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_post_service_proto_goTypes,
		DependencyIndexes: file_posts_post_service_proto_depIdxs,
	}.Build()
	File_posts_post_service_proto = out.File
	file_posts_post_service_proto_goTypes = nil
	file_posts_post_service_proto_depIdxs = nil
}
