// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: posts/post_message.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostType int32

const (
	PostType_UNKNOWN    PostType = 0
	PostType_DISKUSI    PostType = 1
	PostType_MATERIAL   PostType = 2
	PostType_TASK       PostType = 3
	PostType_CONFERENCE PostType = 4
	PostType_QUIZ       PostType = 5
	PostType_INFO       PostType = 6
)

// Enum value maps for PostType.
var (
	PostType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DISKUSI",
		2: "MATERIAL",
		3: "TASK",
		4: "CONFERENCE",
		5: "QUIZ",
		6: "INFO",
	}
	PostType_value = map[string]int32{
		"UNKNOWN":    0,
		"DISKUSI":    1,
		"MATERIAL":   2,
		"TASK":       3,
		"CONFERENCE": 4,
		"QUIZ":       5,
		"INFO":       6,
	}
)

func (x PostType) Enum() *PostType {
	p := new(PostType)
	*p = x
	return p
}

func (x PostType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostType) Descriptor() protoreflect.EnumDescriptor {
	return file_posts_post_message_proto_enumTypes[0].Descriptor()
}

func (PostType) Type() protoreflect.EnumType {
	return &file_posts_post_message_proto_enumTypes[0]
}

func (x PostType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostType.Descriptor instead.
func (PostType) EnumDescriptor() ([]byte, []int) {
	return file_posts_post_message_proto_rawDescGZIP(), []int{0}
}

type Post struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId   string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId   string                 `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Type             PostType               `protobuf:"varint,4,opt,name=type,proto3,enum=posts.PostType" json:"type,omitempty"`
	TypeId           string                 `protobuf:"bytes,5,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Title            string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	FileType         string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	StorageId        string                 `protobuf:"bytes,9,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source           string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	IsAllowToComment bool                   `protobuf:"varint,11,opt,name=is_allow_to_comment,json=isAllowToComment,proto3" json:"is_allow_to_comment,omitempty"`
	IsPublished      bool                   `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	UpdatedBy        string                 `protobuf:"bytes,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_post_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_post_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_post_message_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *Post) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *Post) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_UNKNOWN
}

func (x *Post) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Post) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Post) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *Post) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Post) GetIsAllowToComment() bool {
	if x != nil {
		return x.IsAllowToComment
	}
	return false
}

func (x *Post) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Post) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Post) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Post) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_posts_post_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_posts_post_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_posts_post_message_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Comment) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Comment) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *Comment) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_posts_post_message_proto protoreflect.FileDescriptor

const file_posts_post_message_proto_rawDesc = "" +
	"\n" +
	"\x18posts/post_message.proto\x12\x05posts\"\xe3\x03\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x03 \x01(\tR\x0etopicSubjectId\x12#\n" +
	"\x04type\x18\x04 \x01(\x0e2\x0f.posts.PostTypeR\x04type\x12\x17\n" +
	"\atype_id\x18\x05 \x01(\tR\x06typeId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"storage_id\x18\t \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12-\n" +
	"\x13is_allow_to_comment\x18\v \x01(\bR\x10isAllowToComment\x12!\n" +
	"\fis_published\x18\f \x01(\bR\visPublished\x12\x1d\n" +
	"\n" +
	"updated_by\x18\r \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\xad\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt*`\n" +
	"\bPostType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aDISKUSI\x10\x01\x12\f\n" +
	"\bMATERIAL\x10\x02\x12\b\n" +
	"\x04TASK\x10\x03\x12\x0e\n" +
	"\n" +
	"CONFERENCE\x10\x04\x12\b\n" +
	"\x04QUIZ\x10\x05\x12\b\n" +
	"\x04INFO\x10\x06B\x10Z\x0epb/posts;postsb\x06proto3"

var (
	file_posts_post_message_proto_rawDescOnce sync.Once
	file_posts_post_message_proto_rawDescData []byte
)

func file_posts_post_message_proto_rawDescGZIP() []byte {
	file_posts_post_message_proto_rawDescOnce.Do(func() {
		file_posts_post_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_post_message_proto_rawDesc), len(file_posts_post_message_proto_rawDesc)))
	})
	return file_posts_post_message_proto_rawDescData
}

var file_posts_post_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_posts_post_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_posts_post_message_proto_goTypes = []any{
	(PostType)(0),   // 0: posts.PostType
	(*Post)(nil),    // 1: posts.Post
	(*Comment)(nil), // 2: posts.Comment
}
var file_posts_post_message_proto_depIdxs = []int32{
	0, // 0: posts.Post.type:type_name -> posts.PostType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_posts_post_message_proto_init() }
func file_posts_post_message_proto_init() {
	if File_posts_post_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_post_message_proto_rawDesc), len(file_posts_post_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_posts_post_message_proto_goTypes,
		DependencyIndexes: file_posts_post_message_proto_depIdxs,
		EnumInfos:         file_posts_post_message_proto_enumTypes,
		MessageInfos:      file_posts_post_message_proto_msgTypes,
	}.Build()
	File_posts_post_message_proto = out.File
	file_posts_post_message_proto_goTypes = nil
	file_posts_post_message_proto_depIdxs = nil
}
